// Geschenkideen nach Kategorie und Geschlecht
// Struktur: category -> gender -> array of gift ideas

const AMAZON_AFFILIATE_TAG = process.env.NEXT_PUBLIC_AMAZON_AFFILIATE_TAG || 'httpwwwspor03-21';

const addAffiliateTag = (url) => {
  if (!url) return '';
  if (url.includes('?')) {
    return `${url}&tag=${AMAZON_AFFILIATE_TAG}`;
  }
  return `${url}?tag=${AMAZON_AFFILIATE_TAG}`;
};

export const GIFT_IDEAS_BY_CATEGORY = {
  tech: {
    label: '💻 Technik & Gadgets',
    emoji: '💻',
    genders: {
      female: [
        { name: 'Mini-Fotodrucker fürs Handy (Bluetooth)', price: 89.99, link: addAffiliateTag('https://www.amazon.de/s?k=mini+fotodrucker') },
        { name: 'LED-Lichtspiegel fürs Schminken', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+spiegel') },
        { name: 'Kabellose Wärmflasche mit Powerbank', price: 39.99, link: addAffiliateTag('https://www.amazon.de/s?k=wärmflasche') },
        { name: 'Stylischer Cable-Organizer', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=kabel+organizer') },
        { name: 'Smart Mug Warmer', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=mug+warmer') },
        { name: 'Selfie-Ringlicht zum Anklemmen', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=ringlicht') },
        { name: 'Mini-Beamer für Filmnächte', price: 79.99, link: addAffiliateTag('https://www.amazon.de/s?k=mini+beamer') },
        { name: 'Taschenlampe im Lippenstift-Design', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=taschenlampe') },
        { name: 'Bluetooth-Sleep-Headband', price: 44.99, link: addAffiliateTag('https://www.amazon.de/s?k=sleep+headband') },
        { name: 'Magnetische Ladekabel-Clips', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=ladekabel+clips') },
        { name: 'Bluetooth-Duschlautsprecher', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=duschlautsprecher') },
        { name: 'USB-Tassenwärmer in Tierform', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=tassenwärmer') },
        { name: 'Mini-Ventilator fürs Handy', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=ventilator+handy') },
        { name: 'Smart-LED-Lichtleiste für Spiegel', price: 31.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+lichtleiste') },
        { name: 'Digitaler Bilderrahmen Mini', price: 35.99, link: addAffiliateTag('https://www.amazon.de/s?k=bilderrahmen') },
        { name: 'Bluetooth-Tracker im Anhänger', price: 26.99, link: addAffiliateTag('https://www.amazon.de/s?k=tracker+anhänger') },
        { name: 'Hand-Handyhalter für Bett', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=handyhalter') },
        { name: 'Kabeltasche mit Patch', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=kabel+tasche') },
        { name: 'Handwärmer mit USB-Aufladung', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=handwärmer') },
        { name: 'Tisch-LED-Lampe Touch-dimmbar', price: 27.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+lampe') },
        { name: 'Elektrischer Milchaufschäumer Reise', price: 28.99, link: addAffiliateTag('https://www.amazon.de/s?k=milchaufschäumer') },
        { name: 'Bluetooth-Tastatur für Tablet', price: 32.99, link: addAffiliateTag('https://www.amazon.de/s?k=bluetooth+tastatur') },
        { name: 'Mini-Dokumentenscanner', price: 25.99, link: addAffiliateTag('https://www.amazon.de/s?k=dokumentenscanner') },
        { name: 'USB-Staubsauger für Tastatur', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=staubsauger') },
        { name: 'Anti-Lost Tag Design', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=airtag+holder') },
        { name: 'Kompakte Powerbank mit LED', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=powerbank') },
        { name: 'USB-C Adapter Multi-Port', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=usb+adapter') },
        { name: 'Wireless Charging Pad Design', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=wireless+charger') },
        { name: 'Kopfhörer Wireless In-Ear', price: 39.99, link: addAffiliateTag('https://www.amazon.de/s?k=kopfhörer+wireless') },
        { name: 'Smart-Haarbürste mit LED', price: 37.99, link: addAffiliateTag('https://www.amazon.de/s?k=smart+haarbürste') }
      ],
      male: [
        { name: 'Kurbelradio mit Solar-Panel', price: 44.99, link: addAffiliateTag('https://www.amazon.de/s?k=kurbelradio') },
        { name: 'Mini-Drohne mit Flugmodi', price: 79.99, link: addAffiliateTag('https://www.amazon.de/s?k=drohne+mini') },
        { name: 'Bluetooth-In-Ear-Kopfhörer robust', price: 49.99, link: addAffiliateTag('https://www.amazon.de/s?k=kopfhörer+robust') },
        { name: 'USB-Raketenwerfer Schreibtisch', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=raketenwerfer') },
        { name: 'Multitool-Ladekabel', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=multitool+kabel') },
        { name: 'LED-Stirnlampe mit Sensor', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=stirnlampe') },
        { name: 'Retro-Spielkonsole Mini', price: 49.99, link: addAffiliateTag('https://www.amazon.de/s?k=retro+konsole') },
        { name: 'Smart-Schlüsselanhänger Flaschenöffner', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=schlüsselanhänger') },
        { name: 'Mini-Projektor für FIFA', price: 89.99, link: addAffiliateTag('https://www.amazon.de/s?k=mini+projektor') },
        { name: 'Digitales Multimeter', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=multimeter') },
        { name: 'Bluetooth-Ortungs-Tag Fahrrad', price: 27.99, link: addAffiliateTag('https://www.amazon.de/s?k=tracker+fahrrad') },
        { name: 'Kabelmanagement Set', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=kabelmanagement') },
        { name: 'Externe SSD Rugged Mini', price: 89.99, link: addAffiliateTag('https://www.amazon.de/s?k=externe+ssd') },
        { name: 'USB-C Dockingstation Mini', price: 49.99, link: addAffiliateTag('https://www.amazon.de/s?k=usb+c+dock') },
        { name: 'Anti-Stress Clicker', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=fidget+clicker') },
        { name: 'Solar-Powerbank Karabiner', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=solar+powerbank') },
        { name: 'Karabiner-Gadget Multitool', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=karabiner+multitool') },
        { name: 'LED-Leuchtstreifen Monitor', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+streifen') },
        { name: 'Netzwerk-Testgerät', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=netzwerk+tester') },
        { name: 'Raspberry-Pi Mini-Gadget', price: 69.99, link: addAffiliateTag('https://www.amazon.de/s?k=raspberry+pi') },
        { name: 'Handy-Gaming-Controller', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=game+controller') },
        { name: 'Duschradio mit Saugnapf', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=duschradio') },
        { name: 'Time-Timer-Uhr Digital', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=timer+uhr') },
        { name: 'Noise Sensor Gadget', price: 28.99, link: addAffiliateTag('https://www.amazon.de/s?k=sound+meter') },
        { name: 'Smartphone-Stativ Tasche', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=stativ') },
        { name: 'USB-Hub 7-in-1', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=usb+hub') },
        { name: 'Webcam HD mit Mikrofon', price: 39.99, link: addAffiliateTag('https://www.amazon.de/s?k=webcam') },
        { name: 'Externe Festplatte 2TB', price: 59.99, link: addAffiliateTag('https://www.amazon.de/s?k=festplatte') },
        { name: 'Laptop-Ständer ergonomisch', price: 32.99, link: addAffiliateTag('https://www.amazon.de/s?k=laptop+ständer') },
        { name: 'Mechanische Tastatur Gaming', price: 79.99, link: addAffiliateTag('https://www.amazon.de/s?k=mechanische+tastatur') }
      ]
    }
  },
  lifestyle: {
    label: '🌿 Lifestyle & Wellness',
    emoji: '🌿',
    genders: {
      female: [
        { name: 'DIY-Spa-Set (Badekugeln, Masken)', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=spa+set') },
        { name: 'Achtsamkeits-Kartenset Daily Rituals', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=achtsamkeit+karten') },
        { name: 'Wärmflasche mit kuscheligem Bezug', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=wärmflasche') },
        { name: 'Duftkerzen-Set winterlich', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=duftkerzen') },
        { name: 'Seidene Schlafmaske + Ohrstöpsel', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=schlafmaske') },
        { name: 'Handlettering-Starterset', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=handlettering') },
        { name: 'Selfcare-Journal geführt', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=journal') },
        { name: 'Yogablock + hübsches Handtuch', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=yoga+set') },
        { name: 'Guasha-Stein oder Massageroller', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=guasha+stein') },
        { name: 'Tee-Tasting-Box besondere Sorten', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=tee+set') },
        { name: 'Gratitude-Glas mit Zetteln', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=gratitude+jar') },
        { name: 'Haargummi-Set aus Satin', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=haargummi+satin') },
        { name: 'Mini-Aroma-Diffuser Schreibtisch', price: 25.99, link: addAffiliateTag('https://www.amazon.de/s?k=aroma+diffuser') },
        { name: 'Massageball-Set', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=massageball') },
        { name: 'Digital Detox Box', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=notizbuch+set') },
        { name: 'Handcreme-Trio Winterduft', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=handcreme+set') },
        { name: 'Fusspeeling & Kuschelsocken Set', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=fusspeeling') },
        { name: 'Kakao-Ritual-Set hochwertiger Kakao', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=kakao+ritual') },
        { name: 'Affirmationskarten starke Frauen', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=affirmation+karten') },
        { name: 'Kalender Selbstfürsorge-Challenges', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=kalender') },
        { name: 'Duftbeutel Schlafzimmer/Schrank', price: 8.99, link: addAffiliateTag('https://www.amazon.de/s?k=duftbeutel') },
        { name: 'DIY-Fotocollage Bilderrahmen', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=bilderrahmen+collage') },
        { name: 'Wärmende Schulter-/Nackenauflage', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=nackenauflage') },
        { name: 'Mini-Kräutergarten Fensterbank', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=kräutergarten') },
        { name: 'Me-Time Gutscheinblock witzig', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=gutschein') },
        { name: 'Entspannungs-Creme-Set Premium', price: 26.99, link: addAffiliateTag('https://www.amazon.de/s?k=creme+set') },
        { name: 'Bath Bombs Variety Pack', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=bath+bombs') },
        { name: 'Face Mask Sheet Set', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=face+masks') },
        { name: 'Ätherische Öle Set Wellness', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=ätherische+öle') },
        { name: 'Meditation Cushion Premium', price: 35.99, link: addAffiliateTag('https://www.amazon.de/s?k=meditationskissen') }
      ],
      male: [
        { name: 'Bartpflege-Set Öl, Kamm, Balsam', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=bartpflege+set') },
        { name: 'Männliche Duftkerze', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=duftkerze+männer') },
        { name: 'Hochwertiger Rasierpinsel + Seife', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=rasierpinsel') },
        { name: 'Nackenmassage-Kissen Sofa', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=nackenmassage') },
        { name: 'Craft-Beer-Seife oder Kaffee-Peeling', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=beer+soap') },
        { name: 'Schlafmaske + Ohrstöpsel schlicht', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=schlafmaske') },
        { name: 'Morning Routine Notizblock', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=habit+tracker') },
        { name: 'Mini-Stretch-Band-Set mit Anleitung', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=stretch+bands') },
        { name: 'Thermobecher robuster Outdoor-Look', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=thermobecher') },
        { name: 'Cold Shower Challenge Poster', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=poster') },
        { name: 'Handcreme + Lippenbalsam Workman', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=handcreme') },
        { name: 'Mini-Aroma-Diffuser Holzoptik', price: 25.99, link: addAffiliateTag('https://www.amazon.de/s?k=diffuser') },
        { name: 'Fußmassage-Rolle Schreibtisch', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=fußmassage') },
        { name: 'Chillout Playlist QR-Code Rahmen', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=rahmen') },
        { name: 'Männerpflege-Probenset', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=männerpflege+set') },
        { name: 'Sporttuch mit Motivation', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=sporttuch') },
        { name: 'Grillmeister-Schürze mit Message', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=schürze') },
        { name: 'Saunagutschein oder Sauna-Set', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=sauna+set') },
        { name: 'Thermalwasser-Spray Büro/Gym', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=thermalwasser+spray') },
        { name: 'Kleines Meditationskissen', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=meditationskissen') },
        { name: '30-Tage-Challenge Kartenset', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=challenge+karten') },
        { name: 'Outdoor-Emaillebecher mit Namen', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=emaillebecher') },
        { name: 'Kompakter Kulturbeutel mit Haken', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=kulturbeutel') },
        { name: 'DIY-Anti-Stress-Glas', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=stress+relief') },
        { name: 'Mini-Räucherstäbchen-Set mit Halter', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=räucherstäbchen') },
        { name: 'Beard Growth Kit Premium', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=bart+wachstum') },
        { name: 'Deep Sleep Pillow Spray', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=schlafspray') },
        { name: 'Massage Roller für Muskeln', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=massage+roller') },
        { name: 'Aromatherapy Essential Oils', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=essential+oils') },
        { name: 'Premium Shaving Kit', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=rasierset') }
      ]
    }
  },
  home: {
    label: '🏠 Home & Deko',
    emoji: '🏠',
    genders: {
      female: [
        { name: 'Makramee-Wandbehang oder DIY-Kit', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=makramee+wandbehang') },
        { name: 'Lichterkette mit Clips Fotos', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=lichterkette+clips') },
        { name: 'Trockenblumen-Bouquet im Glas', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=trockenblumen') },
        { name: 'LED-Kerzen mit Timer', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+kerzen') },
        { name: 'Personalisierte Tasse Insider-Spruch', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=tasse+personalisiert') },
        { name: 'Schneekugel mit Foto', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=schneekugel') },
        { name: 'Metallkerzenhalter Minimal', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=kerzenhalter') },
        { name: 'Memory-Board Magnet Pinwand', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=memory+board') },
        { name: 'Fensterbilder Nordic-Stil', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=fenstersticker') },
        { name: 'Mini-Vase-Set 3er', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=vase+set') },
        { name: 'Duft-Stäbchen dekorative Flasche', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=duft+stäbchen') },
        { name: 'Glasuntersetzer selbst gestaltet', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=untersetzer+glas') },
        { name: 'Küchenhandtuch-Set Farben', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=küchenhandtuch') },
        { name: 'Briefpapier-Set Sticker', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=briefpapier') },
        { name: 'Deko-Tablett Kerzen', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=tablett+deko') },
        { name: 'Dekokissen Wintermotiv', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=kissen+winter') },
        { name: 'Magnetische Posterleisten Poster', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=posterleisten') },
        { name: 'Emaille-Schild witziger Spruch', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=email+schild') },
        { name: 'Kleine Schmuckschale', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=schmuckschale') },
        { name: 'Mini-Regal für Gewürze', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=mini+regal') },
        { name: 'Fotohalter Holz Metallclip', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=fotohalter') },
        { name: 'Glasflasche mit Lichterkette', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=glasflasche+licht') },
        { name: 'Untersetzer Schallplatten-Optik', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=untersetzer') },
        { name: 'Dekorative Hakenleiste', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=hakenleiste') },
        { name: 'Duft-Säckchen Kleiderschrank', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=duft+säckchen') },
        { name: 'Wanddeko Minimalist Print', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=wanddeko') },
        { name: 'Türkranz Willkommen', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=türkranz') },
        { name: 'Baldachin Himmel Schlafzimmer', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=baldachin') },
        { name: 'Wandregale Floating Holz', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=wandregal') },
        { name: 'Deko-Schriftzug Holz', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=schriftzug+holz') }
      ],
      male: [
        { name: 'Metall-Poster Retro Fußball/Marvel', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=metall+poster') },
        { name: 'Beton-Deko Stifthalter', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=beton+deko') },
        { name: 'Wandhalterung Kopfhörer', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=kopfhörer+halterung') },
        { name: 'Untersetzer Stadion-Design', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=untersetzer+stadion') },
        { name: 'Neon LED-Schriftzug Game On', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=neon+schriftzug') },
        { name: 'Magnetische Flaschenöffner Wand', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=flaschenöffner+magnet') },
        { name: 'Emaille-Becher Wandhaken', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=emaille+becher') },
        { name: 'Deko-Kissen minimalistisch', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=kissen+minimalist') },
        { name: 'Holz-Bierträger Deko', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=bierträger') },
        { name: 'Bartpflege-Organizer Bad', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=bartpflege+organizer') },
        { name: 'Mini-Regal Funko Pops', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=funko+pop+regal') },
        { name: 'Poster Planets Sonnensystem', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=poster+planets') },
        { name: 'Lern-Tafel Kreidetafel', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=kreidetafel') },
        { name: 'Wand-Flaschenregal 2-3 Plätze', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=flaschenregal') },
        { name: 'Schlüsselbrett mit Magnetleiste', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=schlüsselbrett') },
        { name: 'Magnetische Kabelhalter', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=kabelhalter+magnet') },
        { name: 'Stifthalter Werkzeug-Look', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=stifthalter') },
        { name: 'Parking Only Metallschild', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=parking+schild') },
        { name: 'Mini-Pflanze Betontopf', price: 10.99, link: addAffiliateTag('https://www.amazon.de/s?k=sukkulenten') },
        { name: 'LED-Strip Regal TV', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=led+strip') },
        { name: 'Aufbewahrungsbox Vintage', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=box+vintage') },
        { name: 'Wandkalender Sport Technik', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=kalender+sport') },
        { name: 'Rules of the Man Cave Bild', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=man+cave+rules') },
        { name: 'Buchstützen Figuren Batman', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=buchstütze') },
        { name: 'Tischuhr Retro-Radiodesign', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=uhr+retro') },
        { name: 'Wandhalterung Controller', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=controller+halter') },
        { name: 'Laserdruck Geschenke Poster', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=poster+print') },
        { name: 'Industrielampe Deko', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=lampe+industrial') },
        { name: 'Holzrahmen Stadtplan', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=stadtplan+rahmen') },
        { name: 'Gaming-Schreibtisch Organizer', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=organizer+schreibtisch') }
      ]
    }
  },
  sports: {
    label: '⚽ Sport & Fitness',
    emoji: '⚽',
    genders: {
      female: [
        { name: 'Hübsche Trinkflasche Edelstahl', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=trinkflasche') },
        { name: 'Widerstandsband-Set Beutel', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=widerstandsbänder') },
        { name: 'Yoga- Pilates-Ball Pastell', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=yoga+ball') },
        { name: 'Springseil mit Zähler', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=springseil') },
        { name: 'Mini-Faszienrolle Füße', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=faszienrolle') },
        { name: 'Sport-Haargummis + Stirnband', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=haargummi+sport') },
        { name: 'Workout-Karten Home-Workouts', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=workout+karten') },
        { name: 'Trainings-Tagebuch Habit-Tracker', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=trainings+tagebuch') },
        { name: 'Smartphone-Armband Joggen', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=armband+handy') },
        { name: 'Kühltuch nach dem Sport', price: 10.99, link: addAffiliateTag('https://www.amazon.de/s?k=cooling+towel') },
        { name: 'Schweißband-Set Stirn Handgelenk', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=schweißband') },
        { name: 'Balance-Pad Kissen', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=balance+pad') },
        { name: 'Mini-Hula-Hoop zerlegbar', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=hula+hoop') },
        { name: 'Core-Slider Gleiter', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=slider+training') },
        { name: 'Fitness-Poster 10-Minuten', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=fitness+poster') },
        { name: 'Sport-Socken mit Motiv', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=sport+socken') },
        { name: 'Gym-Bag cooler Print', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=gym+bag') },
        { name: 'Timer Mini-Stoppuhr', price: 8.99, link: addAffiliateTag('https://www.amazon.de/s?k=stoppuhr') },
        { name: 'Massage-Ball-Set', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=massage+ball') },
        { name: 'Minibuch Desk-Stretching', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=stretching+buch') },
        { name: 'Handtrainer Grip-Trainer', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=grip+trainer') },
        { name: 'Fahrrad-Handschuhe', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=fahrrad+handschuhe') },
        { name: 'Mini-Foamroller Reisegröße', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=foam+roller') },
        { name: 'Ankle Weights Fußgewichte', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=ankle+weights') },
        { name: 'Move every day Challenge-Block', price: 10.99, link: addAffiliateTag('https://www.amazon.de/s?k=challenge+block') },
        { name: 'Yoga-Matte rutschfest', price: 24.99, link: addAffiliateTag('https://www.amazon.de/s?k=yoga+matte') },
        { name: 'Stretchband Flexibilität', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=stretchband') },
        { name: 'Sportrucksack Daypack', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=sportrucksack') },
        { name: 'Trainingsleggings Premium', price: 39.99, link: addAffiliateTag('https://www.amazon.de/s?k=leggings+sport') },
        { name: 'Laufuhr oder Fitness-Uhr', price: 79.99, link: addAffiliateTag('https://www.amazon.de/s?k=fitness+uhr') }
      ],
      male: [
        { name: 'Springseil Stahlseil Speed Rope', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=speed+rope') },
        { name: 'Push-Up-Griffe bessere Liegestütze', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=push+up+griffe') },
        { name: 'Widerstandsband-Set hart/mittel', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=widerstands+bands') },
        { name: 'Handgrip-Trainer verstellbar', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=hand+grip+trainer') },
        { name: 'Fußball-Mini-Tor Garten', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=mini+tor') },
        { name: 'Mini-Basketballkorb Tür', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=basketball+korb') },
        { name: 'Shaker-Bottle Pulverfach', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=shaker+bottle') },
        { name: 'Fußball-Running-Socken hochwertig', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=socken+sport') },
        { name: 'Cooling-Towel Training', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=cooling+towel') },
        { name: 'Faszienrolle robust', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=faszienrolle+robust') },
        { name: 'Agility-Leiter Koordination', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=agility+leiter') },
        { name: 'Trainingshandschuhe Gym', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=gym+handschuhe') },
        { name: 'Work Out Logbook PRs', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=workout+journal') },
        { name: 'Intervall-Timer Gym', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=interval+timer') },
        { name: 'Mini-Balanceboard Holz', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=balance+board') },
        { name: 'Sport-Bauchtasche Laufen', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=lauf+tasche') },
        { name: 'Dehn-Stretching-Gurt', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=stretch+strap') },
        { name: 'Resistance-Tube Türanker', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=resistance+tube') },
        { name: 'Kinesio-Tape Kleinpackung', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=kinesio+tape') },
        { name: 'Blackroll-Ball Triggerpunkte', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=blackroll') },
        { name: 'Badetuch Team-Vereinslook', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=badetuch') },
        { name: '30-Tage-Plank-Challenge Poster', price: 9.99, link: addAffiliateTag('https://www.amazon.de/s?k=plank+challenge') },
        { name: 'Massage-Gun Mini-Version', price: 34.99, link: addAffiliateTag('https://www.amazon.de/s?k=massage+gun') },
        { name: 'Fußball-Skill-Trainer Ball', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=skill+trainer') },
        { name: 'Tischtennis-Set Netz Schläger', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=tischtennis+set') },
        { name: 'Boxhandschuhe Training', price: 29.99, link: addAffiliateTag('https://www.amazon.de/s?k=boxhandschuhe') },
        { name: 'Sprung-Stelzen Höhe Jump', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=jump+stilts') },
        { name: 'Hantel-Set Gewichte', price: 49.99, link: addAffiliateTag('https://www.amazon.de/s?k=hantel+set') },
        { name: 'Schwimmtasche wasserdicht', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=schwimm+tasche') },
        { name: 'Trainingsanzug Premium', price: 59.99, link: addAffiliateTag('https://www.amazon.de/s?k=trainingsanzug') }
      ]
    }
  },
  books: {
    label: '📚 Bücher & Wissen',
    emoji: '📚',
    genders: {
      female: [
        { name: 'Kreatives Schreibjournal 100 Fragen', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=schreibjournal') },
        { name: 'Illustriertes Kochbuch One-Pot', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=kochbuch+illustration') },
        { name: 'Feministische Comic-Essays', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=feminist+comics') },
        { name: 'Bildband Reiseziele & Bucket-List', price: 21.99, link: addAffiliateTag('https://www.amazon.de/s?k=bildband+reisen') },
        { name: '5-Minuten-Geschichten Bett', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=kurzgeschichten') },
        { name: 'Escape-Room-Buch Zuhause', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=escape+room+buch') },
        { name: 'Bullet-Journal-Guide + Notizbuch', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=bullet+journal') },
        { name: 'Psychologie-Buch Alltagsgefühle', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=psychologie+buch') },
        { name: 'Urban Sketching / Handlettering Guide', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=sketching+buch') },
        { name: 'Starke Frauen Geschichte Kartenset', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=frauengeschichte') },
        { name: 'Habit-Building Mini-Gewohnheiten', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=habits+buch') },
        { name: 'Fragen an Freunde Spieleabend', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=fragekarten') },
        { name: 'Hörbuch-Gutschein + Empfehlungsliste', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=hörbuch') },
        { name: 'Mini-Enzyklopädie Pflanzen & Kräuter', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=pflanzenenzyklopädie') },
        { name: 'Kalender tägliche Wissens-Snacks', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=wissens+kalender') },
        { name: 'Plot your Life Lebensplanung', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=lebensplanung') },
        { name: 'Sachbuch Schlaf & Ernährung', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=gesundheit+buch') },
        { name: 'Graphic Novel moderne Hauptfigur', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=graphic+novel+frauen') },
        { name: 'Sprachlern-Buch mit Dialogen', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=sprachbuch') },
        { name: 'Mini-Wörterbuch Slang & Memes', price: 10.99, link: addAffiliateTag('https://www.amazon.de/s?k=wörterbuch') },
        { name: 'Philosophie to go kurze Texte', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=philosophie+tasche') },
        { name: 'Rätselbuch Logik & Nonogramme', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=rätselbuch') },
        { name: 'Was ich an dir liebe Ausfüllbuch', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=ausfüllbuch') },
        { name: 'Alltagsfeminismus & Body Positivity', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=feminismus+buch') },
        { name: '100 Dinge Bucket-List Buch', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=bucket+list') },
        { name: 'Romans mit starker Protagonistin', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=frauenroman') },
        { name: 'Kreativbuch DIY Deko & Design', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=deko+diy') },
        { name: 'Mentalität & Erfolgs-Mindset', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=mindset+buch') },
        { name: 'Reiseguide unbekannte Orte', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=reiseguide') },
        { name: 'Kunstgeschichte leicht erklärt', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=kunstgeschichte') }
      ],
      male: [
        { name: 'Entscheidungstheorie Thinking in Bets', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=entscheidung+buch') },
        { name: 'Sportpsychologie Mentaltraining', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=sportpsychologie') },
        { name: 'Biografie Sportler/Unternehmer', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=biografie') },
        { name: 'How-To Holzbearbeitung & Skills', price: 19.99, link: addAffiliateTag('https://www.amazon.de/s?k=holzbearbeitung') },
        { name: 'Wissenschaftsbuch Physik/Astronomie', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=wissenschaft+buch') },
        { name: 'Geld & Finanzen einfach erklärt', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=finanzen+buch') },
        { name: '100 Erfindungen veränderten Welt', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=erfindungen') },
        { name: 'Escape-Rätselbuch Thriller', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=escape+buch') },
        { name: 'Papierflugzeug Falt-Buch', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=papierflugzeug') },
        { name: 'Bier/Whisky/Kaffee-Wissen kompakt', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=bier+wissen') },
        { name: 'Life Hacks praktische Tipps', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=life+hacks') },
        { name: 'Stoische Philosophie Alltag', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=stoizismus') },
        { name: 'Fußball-Taktikbuch oder Sport-Comic', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=fußball+taktik') },
        { name: 'Mathe-Tricks für Erwachsene', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=mathe+tricks') },
        { name: 'Survival-Guide urban/outdoor', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=survival+guide') },
        { name: 'Technik-Geschichte Comicstil', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=technikgeschichte') },
        { name: 'Quiz-Buch Film/Serien/Nerd', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=quiz+buch') },
        { name: 'Erfolgreiche Routinen berühmter Menschen', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=routinen') },
        { name: 'Kleine Geschichte der Zeit', price: 18.99, link: addAffiliateTag('https://www.amazon.de/s?k=stephen+hawking') },
        { name: 'Programmier-Einstiegsbuch', price: 22.99, link: addAffiliateTag('https://www.amazon.de/s?k=programmieren+anfänger') },
        { name: 'Sherlock Holmes Rätselbuch', price: 13.99, link: addAffiliateTag('https://www.amazon.de/s?k=sherlock+holmes') },
        { name: 'Fehlschläge Technikgeschichte', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=fehler+technik') },
        { name: 'Fakten-des-Tages Kartenset', price: 11.99, link: addAffiliateTag('https://www.amazon.de/s?k=fakten+karten') },
        { name: 'Denksportaufgaben Kalender', price: 12.99, link: addAffiliateTag('https://www.amazon.de/s?k=denksport') },
        { name: 'Comic-Sachbuch Klima/Politik', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=sachcomic') },
        { name: 'Gaming & Esports-Ratgeber', price: 17.99, link: addAffiliateTag('https://www.amazon.de/s?k=gaming+guide') },
        { name: 'Strategiebuch Schach/Poker', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=schach+buch') },
        { name: 'Abenteuer-Roman spannend', price: 14.99, link: addAffiliateTag('https://www.amazon.de/s?k=abenteuer+roman') },
        { name: 'Zukunfts-Szenarien Science-Fiction', price: 15.99, link: addAffiliateTag('https://www.amazon.de/s?k=science+fiction') },
        { name: 'Handwerk & Basteln Anleitung', price: 16.99, link: addAffiliateTag('https://www.amazon.de/s?k=handwerk+buch') }
      ]
    }
  }
};

export const getGiftIdeasByCategory = (category, gender = 'all') => {
  const categoryData = GIFT_IDEAS_BY_CATEGORY[category];
  if (!categoryData) return [];

  if (gender === 'all') {
    return [
      ...(categoryData.genders.female || []),
      ...(categoryData.genders.male || [])
    ];
  }

  return categoryData.genders[gender] || [];
};

export const getAllGiftCategories = () => {
  return Object.entries(GIFT_IDEAS_BY_CATEGORY).map(([key, data]) => ({
    id: key,
    label: data.label,
    emoji: data.emoji
  }));
};
